### ISSUE TITLE
aarch64 version installed in amd64 architecture

### ISSUE THREAD

**Issue by Nittarab** [snapcrafters/helm#48]
If I try to use a Helm command inside a shell script I get this error:
`./test.sh: line 2: /usr/local/bin/helm: cannot execute binary file: Exec format error`

Step to reproduce: 
1) create script `test.sh`
```bash
#!/bin/bash -e
helm ls
```
2)  `chmod +x test.sh`
3)  `./test.sh`

helm version:  
installed:   2.15.1            (132) 9MB classic

The problem:
If i run `dpkg --print-architecture`
`amd64`

If I run `file /usr/local/bin/helm`
the output is:
`/usr/local/bin/helm: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped`

**Comment by joedborg** [comment]
Hey @Nittarab,

I think another version of Helm is installed on your system, which is the one you are seeing.  The `helm` binary from the snap should live in `/snap/bin/helm`, rather than `/usr/local/bin/helm`.  This can be tested by running `snap run helm`.

It's likely that `/usr/bin` sits before `/snap/bin` in your PATH, so you'll have to remove `/usr/local/bin/helm` for this to work as expected.

Just to double check, I installed snap version 132 (which is the same as yourself) and ran the same test:

```
file /snap/helm/132/helm
/snap/helm/132/helm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```
(`/snap/bin` contains links)

Let me know if that doesn't work for you and we'll dig a little deeper.

Cheers,
Joe

**Comment by Nittarab** [comment]
Thank you @joedborg, you was right. I deleted the `/usr/local/bin/helm` and now helm work as expected.

**Comment by joedborg** [comment]
No worries @Nittarab, glad we got it sorted!
